# .rubocop.yml

# Define a target Ruby version
AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3.0
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'config/environments/development.rb'